### ISSUE TITLE
DeleteLogFileAction no longer working

### ISSUE THREAD

**Issue by theKBro** [jenkinsci/build-history-manager-plugin#68]
As described in `https://github.com/jenkinsci/jep/blob/master/jep/210/README.adoc`
run.getLogFile() was deprecated and now an unsupported operation exception is thrown

### Jenkins and plugins versions report

Jenkins: 2.375.3
OS: Linux - 4.18.0-425.10.1.el8_7.x86_64

### Reproduction steps

configure a delete log action for any job

### Expected Results

The log should be deleted and no exception should be thrown

### Actual Results

java.lang.UnsupportedOperationException
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getLogFile(WorkflowRun.java:1189)
	at pl.damianszczepanik.jenkins.buildhistorymanager.model.actions.DeleteLogFileAction.perform(DeleteLogFileAction.java:25)
	at pl.damianszczepanik.jenkins.buildhistorymanager.model.Rule.performActions(Rule.java:105)
	at pl.damianszczepanik.jenkins.buildhistorymanager.BuildHistoryManager.perform(BuildHistoryManager.java:64)
	at hudson.model.Job.logRotate(Job.java:472)
	at jenkins.model.JobGlobalBuildDiscarderStrategy.apply(JobGlobalBuildDiscarderStrategy.java:54)
	at jenkins.model.BackgroundGlobalBuildDiscarder.lambda$processJob$0(BackgroundGlobalBuildDiscarder.java:67)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at jenkins.model.BackgroundGlobalBuildDiscarder.processJob(BackgroundGlobalBuildDiscarder.java:61)
	at jenkins.model.BackgroundGlobalBuildDiscarder.execute(BackgroundGlobalBuildDiscarder.java:55)
	at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:102)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by damianszczepanik** [comment]
Based on the reference documentation I think that deleting log file won't be possible in the future. This is because from now API provides handler to the input stream and not the address of the file.

**Comment by theKBro** [comment]
Seems to Work If you want to deleted the Log for the current executed Run, but Not for old Runs only. Like keep 3 Runs, delete logs for all others.

**Comment by damianszczepanik** [comment]
I was able to delete log from build 32 while running build 45

**Comment by theKBro** [comment]
This is still throwing Exceptions like crazy

**Comment by theKBro** [comment]
could you atleast catch java.lang.UnsupportedOperationException here?

**Comment by theKBro** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/jenkinsci/build-history-manager-plugin/pull/175?shareId=967ad855-8460-4dfe-a853-4436ff40ad8b) saved by @theKBro using Copilot Workspace v0.27
